//! Anthropic Admin API usage parser
//!
//! Parses CSV files cached from the Anthropic Admin API usage report.
//! CSV files are stored at ~/.config/tokscale/anthropic-cache/usage.csv
//!
//! CSV Format (generated by tokscale sync):
//! Date,Model,Input,Output,CacheRead,CacheWrite,Cost

use super::UnifiedMessage;
use crate::TokenBreakdown;
use std::path::Path;

/// Parse an Anthropic API usage CSV cache file
pub fn parse_anthropic_api_file(path: &Path) -> Vec<UnifiedMessage> {
    let content = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return vec![],
    };

    let mut messages = Vec::with_capacity(128);
    let mut lines = content.lines();

    let header = match lines.next() {
        Some(h) => h,
        None => return vec![],
    };

    if !header.contains("Date") || !header.contains("Model") {
        return vec![];
    }

    for line in lines {
        if line.trim().is_empty() {
            continue;
        }

        let fields: Vec<&str> = line.split(',').collect();
        if fields.len() < 7 {
            continue;
        }

        let date_str = fields[0].trim();
        let model = fields[1].trim();
        let input: i64 = fields[2].trim().parse().unwrap_or(0);
        let output: i64 = fields[3].trim().parse().unwrap_or(0);
        let cache_read: i64 = fields[4].trim().parse().unwrap_or(0);
        let cache_write: i64 = fields[5].trim().parse().unwrap_or(0);
        let cost: f64 = fields[6].trim().parse().unwrap_or(0.0);

        if model.is_empty() || date_str.is_empty() {
            continue;
        }

        // Parse YYYY-MM-DD to unix timestamp (noon UTC)
        let timestamp = parse_date_to_timestamp(date_str);
        if timestamp == 0 {
            continue;
        }

        messages.push(UnifiedMessage::new(
            "anthropic-api",
            model,
            "anthropic",
            format!("anthropic-api-{}-{}", model, date_str),
            timestamp,
            TokenBreakdown {
                input: input.max(0),
                output: output.max(0),
                cache_read: cache_read.max(0),
                cache_write: cache_write.max(0),
                reasoning: 0,
            },
            cost.max(0.0),
        ));
    }

    messages
}

fn parse_date_to_timestamp(date_str: &str) -> i64 {
    // YYYY-MM-DD format
    if date_str.len() == 10 {
        if let Ok(date) = chrono::NaiveDate::parse_from_str(date_str, "%Y-%m-%d") {
            return date
                .and_hms_opt(12, 0, 0)
                .map(|dt| dt.and_utc().timestamp())
                .unwrap_or(0);
        }
    }
    0
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    #[test]
    fn test_parse_anthropic_api_csv() {
        let mut f = NamedTempFile::new().unwrap();
        writeln!(f, "Date,Model,Input,Output,CacheRead,CacheWrite,Cost").unwrap();
        writeln!(f, "2025-03-01,claude-sonnet-4-20250514,1000,500,200,100,0.0150").unwrap();
        writeln!(f, "2025-03-01,claude-haiku-3-5-20241022,2000,800,0,0,0.0040").unwrap();
        f.flush().unwrap();

        let messages = parse_anthropic_api_file(f.path());
        assert_eq!(messages.len(), 2);

        assert_eq!(messages[0].client, "anthropic-api");
        assert_eq!(messages[0].model_id, "claude-sonnet-4-20250514");
        assert_eq!(messages[0].provider_id, "anthropic");
        assert_eq!(messages[0].tokens.input, 1000);
        assert_eq!(messages[0].tokens.output, 500);
        assert_eq!(messages[0].tokens.cache_read, 200);
        assert_eq!(messages[0].tokens.cache_write, 100);
    }

    #[test]
    fn test_parse_empty_file() {
        let f = NamedTempFile::new().unwrap();
        let messages = parse_anthropic_api_file(f.path());
        assert!(messages.is_empty());
    }

    #[test]
    fn test_parse_date_to_timestamp() {
        assert!(parse_date_to_timestamp("2025-03-01") > 0);
        assert_eq!(parse_date_to_timestamp("invalid"), 0);
        assert_eq!(parse_date_to_timestamp(""), 0);
    }
}
